#!/usr/bin/env sh
fcitx5 &
volumeicon &
parcellite &
/usr/lib/kdeconnectd &
blueberry-tray &
firewall-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
kdeconnect-indicator &
nm-applet &
imwheel &
keepassxc &
mako &
gammastep &
